name: CI Backend Pipeline

on:
  workflow_dispatch

jobs:
  docker-publish:
    name: üê≥ Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: üõé Checkout code
        uses: actions/checkout@v4

      - name: Generate metadata
        id: meta
        shell: bash
        run: |
          current_time=$(date -Iseconds)
          git_description=$(git describe --always --dirty --tags --long)
          linker_flags="-s -X main.buildTime=${current_time} -X main.version=${git_description}"
          echo "linker_flags=${linker_flags}" >> $GITHUB_OUTPUT

      - name: üß∞ Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: üîê Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: üê≥ Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          build-args: |
            LINKER_FLAGS=${{ steps.meta.outputs.linker_flags}}
          tags: |
            vladgrskkh/mrs-api:latest
            vladgrskkh/mrs-api:${{ github.sha }}

      - name: üê≥ Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ./predict_service
          file: ./predict_service/Dockerfile
          push: true
          tags: |
            vladgrskkh/mrs-recommender:latest
            vladgrskkh/mrs-recommender:${{ github.sha }}

  deploy:
    name: üöÄ Deploy to VPS
    needs: docker-publish
    runs-on: ubuntu-latest

    steps:
      - name: üõé Checkout repo
        uses: actions/checkout@v4

      - name: Create .env on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          script: |
            mkdir -p ~/mrs
            mkdir -p ~/mrs/backend
            echo "MRS_DB_DSND=${{ secrets.MRS_DB_DSND }}" > ~/mrs/backend/.env
            echo "SMTP_USERNAMED=${{ secrets.SMTP_USERNAMED }}" >> ~/mrs/backend/.env
            echo "SMTP_PASSWORDD=${{ secrets.SMTP_PASSWORDD }}" >> ~/mrs/backend/.env
            echo "GF_SECURITY_ADMIN_USER=${{ secrets.GF_SECURITY_ADMIN_USER }}" >> ~/mrs/backend/.env
            echo "GF_SECURITY_ADMIN_PASSWORD=${{ secrets.GF_SECURITY_ADMIN_PASSWORD }}" >> ~/mrs/backend/.env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" > ~/mrs/backend/.env_db
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ~/mrs/backend/.env_db
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> ~/mrs/backend/.env_db
            echo "MAILERSEND_API_KEYD=${{ secrets.MAILERSEND_API_KEYD }}" >> ~/mrs/backend/.env
            echo "JWT_SECRET_KEYD=${{ secrets.JWT_SECRET_KEYD }}" >> ~/mrs/backend/.env
            echo "DUCKDNS_TOKEN=${{ secrets.DUCKDNS_TOKEN }}" >> ~/mrs/backend/.env


      - name: üîê Copy files to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          source: "backend/docker-compose.yml,backend/migrations,backend/conf"
          target: "~/mrs/"
          timeout: 120s

      - name: üöÄ Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_PASSPHRASE }}
          timeout: 120s
          script: |
            cd ~/mrs/backend
            docker compose pull
            docker compose down
            docker compose up -d --build
            docker system prune -f
