name: CI Notification Service Pipeline

on:
  push:
    branches:
      - dev/notification-service
      - development
  pull_request:
    branches:
      - dev/notification-service
      - development

jobs:
  build-test:
    name: ðŸ§ª run Test and Linters
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:18
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: mrs
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd "pg_isready -U postgres -d mrs"
    #       --health-interval 5s
    #       --health-timeout 5s
    #       --health-retries 10

    # env:
    #   MRS_DB_DSN: postgres://postgres:postgres@postgres:5432/mrs?sslmode=disable

    steps:
      - name: ðŸ›Ž Checkout code
        uses: actions/checkout@v4

      - name: ðŸ§° Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: ðŸ“¦ Install dependencies
        run: |
          cd notificationservice
          go mod download

    #   - name: ðŸ—„ï¸ Run database migrations
    #     uses: docker://migrate/migrate
    #     with:
    #       args: >
    #         -path=/github/workspace/backend/migrations
    #         -database=${{ env.MRS_DB_DSN }}
    #         up
        
      - name: âœ… Run linters
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.5.0
          working-directory: notificationservice

      - name: ðŸ§ª Run tests
        run: |
          cd notificationservice
          go test ./... -v